module.exports = {
	width:128,
	height:128,
	spark: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	lucene: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	mysql: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	javascript: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	postgresql: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	ampl: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	jupyter: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	git: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	VSCode: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	julia: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	pytorch: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	openNLP: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	keras: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	tensorflow: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	scrapy: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	java: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	sqlServer: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	R: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	python: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	matplotlib: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	sympy: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	scikitLearn:  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	dplyr: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	ggplot2: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	shiny: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	RStudio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	visualStudio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	pandas: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	d3: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	matlab: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	simpleStatistics: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	numpy: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	cuda: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	powerBI: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	DAX: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	weka: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis distinctio maxime fugit quod velit hic, iure",
	wekaA: "The Weka Logo",
	DAXA: "The DAX Logo",
	powerBIA: "The powerBI Logo",
	simpleStatisticsA: "The Simple Statistics Logo",
	cudaA: "The Cuda Logo",
	numpyA: "The Numpy Logo",
	matlabA: "The Matlab Logo",
	d3A: "The D3 Logo",
	pandasA: "The Pandas Logo",
	visualStudioA: "The Visual Studio Logo",
	RStudioA: "The RStudio Logo",
	sparkA: "The Apache Spark Logo",
	luceneA: "The Lucene Logo",
	mysqlA: "The MySQL Logo",
	javascriptA: "The Javascript Logo",
	postgresqlA: "The PostgreSQL Logo",
	amplA: "The Ampl Logo",
	jupyterA: "The Jupyter Logo",
	gitA: "The Git Logo",
	VSCodeA: "The Visual Studio Code Logo",
	juliaA: "The Julia Logo",
	pytorchA: "The Pytorch Logo",
	openNLPA: "The OpenNPL Logo",
	kerasA: "The Keras Logo",
	tensorflowA: "The TensorFlow Logo",
	scrapyA: "The Scrapy Logo",
	javaA: "The Java Logo",
	sqlServerA: "The SQL Server Logo",
	RA: "The R Logo",
	pythonA: "The Python Logo",
	matplotlibA: "The Matplotlib Logo",
	sympy: "The Sympy Logo",
	scikitLearnA: "The Sc",
	dplyrA: "The dplyr Logo",
	ggplot2A: "The ggplot Logo",
	shinyA: "The Shiny Logo"
}
